# Preparing Data to Build h5
This notebook was intended to standardize variable names and add user-generated cutout paths for use in h5 building and ultimately, the classifier. It has been rendered obsolete by the completed SGA 2025 catalog. But it may be worth revisiting if we are in the position of generating our own cutouts in the future.

In [1]:
from catalog_utils import *
from cutout_manager import *
from dataset_builder import *

#### Useful catalogs

In [2]:
sga2020 = "/global/cfs/cdirs/cosmo/data/sga/2020/SGA-2020.fits"
# HDU = 1
sgaBeta2025 = "/global/cfs/cdirs/cosmo/work/legacysurvey/sga/2025/SGA2025-beta-parent-refcat-v1.6.kd.fits"
# HDU = 1

In [9]:
# Load your df to be classified
# df = load_catalog(yourCatalog, optional HDU)
df = load_catalog(sgaBeta2025, 1)
df

,ra,dec,ref_id,mag,fitmode,pa,ba,diam
0,219.925802,-32.530045,4176048,17.780001,0,70.355278,0.583230,0.555508
1,219.891999,-32.342994,4176016,17.709999,0,150.428970,0.460713,0.507900
2,219.940904,-32.331298,242036,17.840000,0,134.882629,0.220731,0.682237
3,220.209215,-32.010931,243654,18.040001,0,91.798492,0.703881,0.507167
4,220.362323,-31.994911,4257822,15.400000,0,10.682078,0.616908,1.066838
...,...,...,...,...,...,...,...,...
470620,30.146677,28.225196,5005050,12.831638,0,162.803253,0.342439,3.757807
470621,30.867045,28.274770,4957379,16.096416,0,84.813797,0.607179,0.527874
470622,30.360603,28.734268,4807432,14.230906,0,54.906796,0.786671,0.765473
470623,30.320490,28.836853,5054143,11.612162,0,1.327161,0.183276,10.501398
470624,30.188173,28.873484,4678425,16.593575,0,137.503754,0.388474,0.498173

In [10]:
# Input the names of the columns that match data columns taken by this program
df = standardize_columns(
    # Required
    df, # your catalog
    ra="ra", # right ascension
    dec="dec", # declination
    id="ref_id", # galaxy IDs
    
    # Optional
    # g_mag="", # magnitude in g-band
    # z_mag="", # magnitude in z-band
    r_mag="mag", # magnitude in r-band
    diam="diam"#, # diameter, ideally 26-isophote
    # morph="", # existing morphology
    # t_type="", # morphology subclass (specific to this program)
    # m_type="", # morphology main class (specific to this program)
    # path="" # path to galaxy image cutout
)

In [11]:
# Optional: input a reference catalog
ref = load_catalog(sga2020, 1)
ref

,SGA_ID,SGA_GALAXY,GALAXY,PGC,RA_LEDA,DEC_LEDA,MORPHTYPE,PA_LEDA,D25_LEDA,BA_LEDA,...,R_COG_PARAMS_M0,R_COG_PARAMS_ALPHA1,R_COG_PARAMS_ALPHA2,R_COG_PARAMS_CHI2,Z_COG_PARAMS_MTOT,Z_COG_PARAMS_M0,Z_COG_PARAMS_ALPHA1,Z_COG_PARAMS_ALPHA2,Z_COG_PARAMS_CHI2,ELLIPSEBIT
0,2,b'SGA-2020 2',b'PGC1283207',1283207,228.377086,5.423202,b'S?',152.199997,0.363078,0.724436,...,0.264044,0.345595,3.303355,0.003811,15.195567,0.298264,0.300107,3.233377,0.011724,0
1,3,b'SGA-2020 3',b'PGC1310416',1310416,202.544438,6.934594,b'Sc',159.259995,0.401791,0.781628,...,0.876432,0.273606,2.499542,0.493439,15.235263,1.309869,0.178668,2.175050,0.203912,0
2,4,b'SGA-2020 4',b'SDSSJ145059.93+135143.0',4435547,222.749787,13.861911,b'S?',44.570000,0.333426,0.663743,...,0.488582,0.278250,3.214446,1.373326,16.807674,0.517704,0.322646,2.900518,1.805409,0
3,7,b'SGA-2020 7',b'PGC1742504',1742504,182.088808,25.602276,b'Sbc',84.970001,0.548277,0.251189,...,0.765731,0.522855,2.304599,0.006013,15.191324,1.040820,0.329563,2.152033,0.004725,0
4,18,b'SGA-2020 18',b'2MASXJ12340801+4535444',3550748,188.533553,45.595643,b'E',168.649994,0.530884,0.695024,...,0.324728,1.743924,2.177483,0.023486,15.124181,0.165473,1.469468,3.394879,0.028654,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383615,5005230,b'SGA-2020 5005230',b'DR8-0774m270-618',-1,77.397511,-27.106348,b'PSF',0.000000,0.332000,1.000000,...,0.231687,0.219425,3.111871,0.016901,16.022186,0.241948,0.201020,3.134553,0.011278,0
383616,5005238,b'SGA-2020 5005238',b'DR8-3541p242-2263',-1,354.025406,24.266276,b'PSF',0.000000,0.553000,1.000000,...,0.241669,0.313603,2.891678,0.068157,15.030018,0.215990,0.324286,2.999769,0.032022,0
383617,5005241,b'SGA-2020 5005241',b'DR8-3598p237-618',-1,359.778524,23.672069,b'PSF',0.000000,0.647000,1.000000,...,0.150522,0.867359,3.746000,0.005017,15.713827,0.251672,0.725019,3.094475,0.004562,0
383618,5005244,b'SGA-2020 5005244',b'DR8-1933p245-3598',-1,193.433580,24.573039,b'PSF',0.000000,0.508000,1.000000,...,8809.708984,0.000040,0.644355,0.112737,15.642013,9365.626953,0.000035,0.740361,0.139232,0
383619,5005247,b'SGA-2020 5005247',b'DR8-2208p192-2734',-1,220.726631,19.287179,b'PSF',0.000000,0.413000,1.000000,...,0.092085,1.242667,4.500690,0.138257,15.551954,0.122381,1.082882,3.906502,0.634644,0

In [15]:
# Input reference columns (currently configured to SGA 2020)
ref = standardize_columns(
    ref,
    ra="RA",
    dec="DEC",
    id="SGA_ID",
    g_mag="G_MAG_SB26",
    z_mag="Z_MAG_SB26",
    r_mag="R_MAG_SB26",
    diam="D26",
    morph="MORPHTYPE",
    # t_type="",
    # m_type="",
    # path=
)

df = remove_reference_catalog(df, ref)
df

,Target_RA,Target_DEC,TargetID,mag_r,fitmode,pa,ba,diam
0,219.925802,-32.530045,4176048,17.780001,0,70.355278,0.583230,0.555508
1,219.891999,-32.342994,4176016,17.709999,0,150.428970,0.460713,0.507900
2,219.940904,-32.331298,242036,17.840000,0,134.882629,0.220731,0.682237
3,220.209215,-32.010931,243654,18.040001,0,91.798492,0.703881,0.507167
4,220.362323,-31.994911,4257822,15.400000,0,10.682078,0.616908,1.066838
...,...,...,...,...,...,...,...,...
188281,29.615824,27.030470,479571,17.910000,0,76.840172,0.569784,0.729297
188282,29.748286,27.061345,3345171,13.347000,0,59.265774,0.714058,0.530304
188283,31.308315,27.139710,3888284,18.170000,0,85.974800,0.698627,0.416352
188284,31.454218,27.408196,3168451,16.190001,0,108.342827,0.860133,0.892261
188285,30.775969,27.506619,1333435,19.167000,0,100.055969,0.822534,0.456332

In [16]:
df, missing = attach_cutout_paths(df, "/cutouts/dr10/")
df

100%|██████████| 188286/188286 [00:01<00:00, 146783.91it/s]

,Target_RA,Target_DEC,TargetID,mag_r,fitmode,pa,ba,diam,Path
0,219.925802,-32.530045,4176048,17.780001,0,70.355278,0.583230,0.555508,
1,219.891999,-32.342994,4176016,17.709999,0,150.428970,0.460713,0.507900,
2,219.940904,-32.331298,242036,17.840000,0,134.882629,0.220731,0.682237,
3,220.209215,-32.010931,243654,18.040001,0,91.798492,0.703881,0.507167,
4,220.362323,-31.994911,4257822,15.400000,0,10.682078,0.616908,1.066838,
...,...,...,...,...,...,...,...,...,...
188281,29.615824,27.030470,479571,17.910000,0,76.840172,0.569784,0.729297,
188282,29.748286,27.061345,3345171,13.347000,0,59.265774,0.714058,0.530304,
188283,31.308315,27.139710,3888284,18.170000,0,85.974800,0.698627,0.416352,
188284,31.454218,27.408196,3168451,16.190001,0,108.342827,0.860133,0.892261,
188285,30.775969,27.506619,1333435,19.167000,0,100.055969,0.822534,0.456332,

In [17]:
missing

['/cutouts/dr10/219/4176048_grz_152_219.9258_-32.5300.fits',
 '/cutouts/dr10/219/4176016_grz_152_219.8920_-32.3430.fits',
 '/cutouts/dr10/219/242036_grz_152_219.9409_-32.3313.fits',
 '/cutouts/dr10/220/243654_grz_152_220.2092_-32.0109.fits',
 '/cutouts/dr10/220/4257822_grz_152_220.3623_-31.9949.fits',
 '/cutouts/dr10/219/4180680_grz_152_219.9722_-31.7186.fits',
 '/cutouts/dr10/219/245155_grz_152_219.5296_-31.6771.fits',
 '/cutouts/dr10/220/4162972_grz_152_220.1520_-31.6634.fits',
 '/cutouts/dr10/220/3864341_grz_152_220.2139_-31.6607.fits',
 '/cutouts/dr10/220/4163396_grz_152_220.1941_-31.6482.fits',
 '/cutouts/dr10/219/4168989_grz_152_219.9406_-31.5276.fits',
 '/cutouts/dr10/219/245757_grz_152_219.8869_-31.5180.fits',
 '/cutouts/dr10/220/3619949_grz_152_220.5202_-31.5180.fits',
 '/cutouts/dr10/220/3626967_grz_152_220.4932_-31.4737.fits',
 '/cutouts/dr10/220/4163313_grz_152_220.2107_-31.4724.fits',
 '/cutouts/dr10/220/4181392_grz_152_220.1968_-31.4668.fits',
 '/cutouts/dr10/220/4172482_grz_152_220.2001_-31.4651.fits',
 '/cutouts/dr10/220/4370541_grz_152_220.2250_-31.4617.fits',
 '/cutouts/dr10/220/246182_grz_152_220.4538_-31.4153.fits',
 '/cutouts/dr10/219/4165088_grz_152_219.5120_-31.3532.fits',
 '/cutouts/dr10/220/3145813_grz_152_220.6920_-31.3487.fits',
 '/cutouts/dr10/219/4177607_grz_152_219.9020_-31.2797.fits',
 '/cutouts/dr10/220/4175081_grz_152_220.0049_-31.2726.fits',
 '/cutouts/dr10/220/3617701_grz_152_220.6273_-31.2389.fits',
 '/cutouts/dr10/220/3613102_grz_152_220.7311_-31.0265.fits',
 '/cutouts/dr10/220/3616249_grz_152_220.6093_-31.0036.fits',
 '/cutouts/dr10/219/248026_grz_152_219.7262_-30.9863.fits',
 '/cutouts/dr10/221/3625581_grz_152_221.1207_-30.8998.fits',
 '/cutouts/dr10/219/4175111_grz_152_219.1958_-33.3712.fits',
 '/cutouts/dr10/219/4163284_grz_152_219.2453_-33.2951.fits',
 '/cutouts/dr10/219/4185355_grz_152_219.4583_-33.0331.fits',
 '/cutouts/dr10/219/4162942_grz_152_219.8243_-32.6569.fits',
 '/cutouts/dr10/219/4163824_grz_152_219.1830_-32.5186.fits',
 '/cutouts/dr10/219/242734_grz_152_219.6760_-32.2018.fits',
 '/cutouts/dr10/219/4190634_grz_152_219.5321_-32.1973.fits',
 '/cutouts/dr10/218/4166176_grz_152_218.6455_-32.0946.fits',
 '/cutouts/dr10/219/243644_grz_152_219.5589_-32.0130.fits',
 '/cutouts/dr10/218/243988_grz_152_218.7645_-31.9413.fits',
 '/cutouts/dr10/218/244090_grz_152_218.8517_-31.9189.fits',
 '/cutouts/dr10/219/4169649_grz_152_219.0928_-31.8877.fits',
 '/cutouts/dr10/218/4169151_grz_152_218.3754_-31.8841.fits',
 '/cutouts/dr10/218/3864283_grz_152_218.4099_-31.8540.fits',
 '/cutouts/dr10/219/13656_grz_152_219.0949_-31.8372.fits',
 '/cutouts/dr10/218/3528947_grz_152_218.3516_-31.8251.fits',
 '/cutouts/dr10/218/4178198_grz_152_218.3392_-31.8162.fits',
 '/cutouts/dr10/218/4165362_grz_152_218.3580_-31.8098.fits',
 '/cutouts/dr10/219/244608_grz_152_219.1820_-31.8042.fits',
 '/cutouts/dr10/218/4167776_grz_152_218.2413_-31.7137.fits',
 '/cutouts/dr10/218/4180699_grz_152_218.4451_-31.7084.fits',
 '/cutouts/dr10/218/4162840_grz_152_218.2388_-31.7083.fits',
 '/cutouts/dr10/218/4175924_grz_152_218.4376_-31.6485.fits',
 '/cutouts/dr10/218/245326_grz_152_218.6903_-31.6381.fits',
 '/cutouts/dr10/218/4257819_grz_152_218.7133_-31.6304.fits',
 '/cutouts/dr10/218/4164172_grz_152_218.3780_-31.5243.fits',
 '/cutouts/dr10/218/4168423_grz_152_218.8745_-31.4836.fits',
 '/cutouts/dr10/218/4169580_grz_152_218.1311_-31.2526.fits',
 '/cutouts/dr10/218/247805_grz_152_218.7838_-31.0334.fits',
 '/cutouts/dr10/218/4164222_grz_152_218.4965_-34.1471.fits',
 '/cutouts/dr10/218/4167101_grz_152_218.3696_-34.0373.fits',
 '/cutouts/dr10/218/3864295_grz_152_218.6002_-33.9760.fits',
 '/cutouts/dr10/218/4163322_grz_152_218.5172_-33.8782.fits',
 '/cutouts/dr10/218/4165010_grz_152_218.3118_-33.8116.fits',
 '/cutouts/dr10/218/3145727_grz_152_218.3835_-33.8046.fits',
 '/cutouts/dr10/218/3145723_grz_152_218.3362_-33.7691.fits',
 '/cutouts/dr10/218/3145725_grz_152_218.3559_-33.7558.fits',
 '/cutouts/dr10/218/4163307_grz_152_218.3339_-33.7443.fits',
 '/cutouts/dr10/218/4257322_grz_152_218.7253_-33.7362.fits',
 '/cutouts/dr10/218/4165128_grz_152_218.2407_-33.7234.fits',
 '/cutouts/dr10/218/4164973_grz_152_218.3827_-33.6752.fits',
 '/cutouts/dr10/218/235532_grz_152_218.3651_-33.4777.fits',
 '/cutouts/dr10/218/4166182_grz_152_218.7595_-33.4680.fits',
 '/cutouts/dr10/218/4182288_grz_152_218.7009_-33.4372.fits',
 '/cutouts/dr10/218/4293884_grz_152_218.7799_-33.2707.fits',
 '/cutouts/dr10/218/4171580_grz_152_218.2996_-33.1883.fits',
 '/cutouts/dr10/218/3145742_grz_152_218.7212_-33.1287.fits',
 '/cutouts/dr10/218/3145741_grz_152_218.6900_-32.9783.fits',
 '/cutouts/dr10/218/803042_grz_152_218.0057_-32.9675.fits',
 '/cutouts/dr10/217/4178360_grz_152_217.7640_-32.9037.fits',
 '/cutouts/dr10/218/4164985_grz_152_218.1118_-32.8518.fits',
 '/cutouts/dr10/218/3160550_grz_152_218.6895_-32.8423.fits',
 '/cutouts/dr10/218/4191186_grz_152_218.7020_-32.6907.fits',
 '/cutouts/dr10/218/4171819_grz_152_218.7007_-32.6875.fits',
 '/cutouts/dr10/218/4165063_grz_152_218.6897_-32.6865.fits',
 '/cutouts/dr10/218/240043_grz_152_218.1011_-32.6739.fits',
 '/cutouts/dr10/218/4168742_grz_152_218.6740_-32.6465.fits',
 '/cutouts/dr10/217/4164303_grz_152_217.9754_-32.6049.fits',
 '/cutouts/dr10/217/3145688_grz_152_217.7286_-32.4957.fits',
 '/cutouts/dr10/218/803276_grz_152_218.5724_-32.4829.fits',
 '/cutouts/dr10/217/241468_grz_152_217.9196_-32.4405.fits',
 '/cutouts/dr10/217/3145697_grz_152_217.8555_-32.4166.fits',
 '/cutouts/dr10/217/4166703_grz_152_217.8706_-32.4030.fits',
 '/cutouts/dr10/218/4174594_grz_152_218.0881_-32.0909.fits',
 '/cutouts/dr10/217/802959_grz_152_217.7545_-32.0476.fits',
 '/cutouts/dr10/217/244328_grz_152_217.3666_-31.8730.fits',
 '/cutouts/dr10/217/4172789_grz_152_217.4277_-31.8328.fits',
 '/cutouts/dr10/217/4166835_grz_152_217.7448_-31.7646.fits',
 '/cutouts/dr10/217/4164359_grz_152_217.4701_-31.6658.fits',
 '/cutouts/dr10/217/4162784_grz_152_217.2449_-31.6597.fits',
 '/cutouts/dr10/218/4168305_grz_152_218.1455_-31.6539.fits',
 '/cutouts/dr10/218/4176848_grz_152_218.1180_-31.6442.fits',
 '/cutouts/dr10/218/4171082_grz_152_218.0155_-31.5820.fits',
 '/cutouts/dr10/217/4178490_grz_152_217.1766_-31.5686.fits',
 '/cutouts/dr10/217/4263508_grz_152_217.4433_-31.4978.fits',
 '/cutouts/dr10/217/4175293_grz_152_217.9405_-31.4592.fits',
 '/cutouts/dr10/217/3864271_grz_152_217.9337_-31.3641.fits',
 '/cutouts/dr10/217/3145692_grz_152_217.7859_-31.2404.fits',
 '/cutouts/dr10/217/247538_grz_152_217.9297_-31.0965.fits',
 '/cutouts/dr10/217/4171600_grz_152_217.9286_-31.0925.fits',
 '/cutouts/dr10/217/4164575_grz_152_217.8528_-31.0689.fits',
 '/cutouts/dr10/217/247725_grz_152_217.6562_-31.0523.fits',
 '/cutouts/dr10/217/4186181_grz_152_217.6660_-31.0428.fits',
 '/cutouts/dr10/217/247860_grz_152_217.0419_-31.0228.fits',
 '/cutouts/dr10/217/4189927_grz_152_217.8267_-30.9720.fits',
 '/cutouts/dr10/217/4164749_grz_152_217.8484_-30.9372.fits',
 '/cutouts/dr10/218/3198082_grz_152_218.1129_-34.3262.fits',
 '/cutouts/dr10/218/4166395_grz_152_218.0641_-34.4994.fits',
 '/cutouts/dr10/218/5078786_grz_152_218.0998_-34.6595.fits',
 '/cutouts/dr10/217/4163612_grz_152_217.8595_-34.3916.fits',
 '/cutouts/dr10/217/229913_grz_152_217.7889_-34.4515.fits',
 '/cutouts/dr10/217/231039_grz_152_217.6729_-34.2639.fits',
 '/cutouts/dr10/217/3145679_grz_152_217.5655_-34.2358.fits',
 '/cutouts/dr10/217/4164502_grz_152_217.6084_-34.3299.fits',
 '/cutouts/dr10/217/4176813_grz_152_217.6471_-34.4493.fits',
 '/cutouts/dr10/217/229067_grz_152_217.6795_-34.5965.fits',
 '/cutouts/dr10/217/4164071_grz_152_217.7319_-34.7619.fits',
 '/cutouts/dr10/217/4171202_grz_152_217.5660_-34.4532.fits',
 '/cutouts/dr10/217/4180867_grz_152_217.6135_-34.5683.fits',
 '/cutouts/dr10/217/4294031_grz_152_217.5636_-34.8742.fits',
 '/cutouts/dr10/217/4164413_grz_152_217.2257_-34.2472.fits',
 '/cutouts/dr10/217/3145681_grz_152_217.6141_-35.0153.fits',
 '/cutouts/dr10/217/3145669_grz_152_217.3822_-34.6243.fits',
 '/cutouts/dr10/217/4163598_grz_152_217.4842_-34.8182.fits',
 '/cutouts/dr10/217/4172830_grz_152_217.2810_-34.5902.fits',
 '/cutouts/dr10/217/4163673_grz_152_217.1073_-34.5567.fits',
 '/cutouts/dr10/217/3145660_grz_152_217.1294_-34.7106.fits',
 '/cutouts/dr10/217/4165855_grz_152_217.4925_-35.4077.fits',
 '/cutouts/dr10/217/4169654_grz_152_217.3757_-35.2659.fits',
 '/cutouts/dr10/217/5073320_grz_152_217.3253_-35.2063.fits',
 '/cutouts/dr10/217/4163013_grz_152_217.3858_-35.3506.fits',
 '/cutouts/dr10/217/224212_grz_152_217.3756_-35.4384.fits',
 '/cutouts/dr10/217/4294091_grz_152_217.2567_-35.4333.fits',
 '/cutouts/dr10/217/4170088_grz_152_217.0071_-35.2634.fits',
 '/cutouts/dr10/215/3614365_grz_152_215.9623_-32.9790.fits',
 '/cutouts/dr10/216/3617951_grz_152_216.2366_-32.9519.fits',
 '/cutouts/dr10/216/238004_grz_152_216.2856_-33.0057.fits',
 '/cutouts/dr10/216/4263657_grz_152_216.3473_-32.9640.fits',
 '/cutouts/dr10/216/3619803_grz_152_216.3267_-32.9918.fits',
 '/cutouts/dr10/216/3145622_grz_152_216.1628_-33.2679.fits',
 '/cutouts/dr10/216/3620485_grz_152_216.5517_-33.0080.fits',
 '/cutouts/dr10/216/3620519_grz_152_216.6191_-33.0230.fits',
 '/cutouts/dr10/216/3630093_grz_152_216.3620_-33.5118.fits',
 '/cutouts/dr10/216/3612292_grz_152_216.8723_-33.1938.fits',
 '/cutouts/dr10/217/3145663_grz_152_217.1745_-33.0939.fits',
 '/cutouts/dr10/217/3145655_grz_152_217.0657_-33.3085.fits',
 '/cutouts/dr10/216/4191675_grz_152_216.5163_-33.9317.fits',
 '/cutouts/dr10/217/4164077_grz_152_217.3585_-33.0244.fits',
 '/cutouts/dr10/216/3614101_grz_152_216.7432_-33.7528.fits',
 '/cutouts/dr10/217/4164923_grz_152_217.4035_-33.0949.fits',
 '/cutouts/dr10/217/4167614_grz_152_217.0413_-33.5256.fits',
 '/cutouts/dr10/217/4172839_grz_152_217.4047_-33.1511.fits',
 '/cutouts/dr10/217/4174976_grz_152_217.1480_-33.4917.fits',
 '/cutouts/dr10/217/4166284_grz_152_217.1409_-33.5125.fits',
 '/cutouts/dr10/216/3145652_grz_152_216.8802_-33.9443.fits',
 '/cutouts/dr10/217/4295071_grz_152_217.2869_-33.4889.fits',
 '/cutouts/dr10/217/4177724_grz_152_217.2254_-33.5595.fits',
 '/cutouts/dr10/217/3145667_grz_152_217.3308_-33.4552.fits',
 '/cutouts/dr10/217/592529_grz_152_217.5214_-33.4791.fits',
 '/cutouts/dr10/217/4168726_grz_152_217.8445_-33.2334.fits',
 '/cutouts/dr10/217/4187840_grz_152_217.8004_-33.2862.fits',
 '/cutouts/dr10/217/590694_grz_152_217.5105_-34.2272.fits',
 '/cutouts/dr10/218/3145716_grz_152_218.1632_-33.7175.fits',
 '/cutouts/dr10/216/246590_grz_152_216.2943_-31.3151.fits',
 '/cutouts/dr10/216/3619725_grz_152_216.2053_-31.4194.fits',
 '/cutouts/dr10/215/3617095_grz_152_215.9681_-30.9143.fits',
 '/cutouts/dr10/215/3620619_grz_152_215.9709_-31.0129.fits',
 '/cutouts/dr10/215/3628451_grz_152_215.7793_-30.9294.fits',
 '/cutouts/dr10/215/3615654_grz_152_215.8257_-31.1894.fits',
 '/cutouts/dr10/215/3612281_grz_152_215.7489_-31.1006.fits',
 '/cutouts/dr10/215/4177885_grz_152_215.7195_-31.2078.fits',
 '/cutouts/dr10/215/3618959_grz_152_215.6210_-31.0408.fits',
 '/cutouts/dr10/215/3623209_grz_152_215.6781_-31.2204.fits',
 '/cutouts/dr10/215/3625604_grz_152_215.6567_-31.1999.fits',
 '/cutouts/dr10/215/3617098_grz_152_215.6035_-31.0826.fits',
 '/cutouts/dr10/215/3616841_grz_152_215.6604_-31.2190.fits',
 '/cutouts/dr10/215/3617247_grz_152_215.5288_-30.9617.fits',
 '/cutouts/dr10/215/5098235_grz_152_215.6455_-31.2396.fits',
 '/cutouts/dr10/215/246733_grz_152_215.6541_-31.2815.fits',
 '/cutouts/dr10/215/3618123_grz_152_215.7724_-31.6670.fits',
 '/cutouts/dr10/215/3615120_grz_152_215.4411_-31.0685.fits',
 '/cutouts/dr10/215/3617730_grz_152_215.6306_-31.5422.fits',
 '/cutouts/dr10/215/3614493_grz_152_215.4552_-31.1794.fits',
 '/cutouts/dr10/215/3624745_grz_152_215.3612_-31.0941.fits',
 '/cutouts/dr10/215/3616602_grz_152_215.3278_-31.0996.fits',
 '/cutouts/dr10/215/3145592_grz_152_215.3431_-31.2416.fits',
 '/cutouts/dr10/215/246829_grz_152_215.3477_-31.2591.fits',
 '/cutouts/dr10/215/5099838_grz_152_215.1595_-31.0789.fits',
 '/cutouts/dr10/215/3615262_grz_152_215.2734_-31.4171.fits',
 '/cutouts/dr10/215/4295076_grz_152_215.3386_-31.7228.fits',
 '/cutouts/dr10/215/3616540_grz_152_215.1784_-31.3558.fits',
 '/cutouts/dr10/215/3622863_grz_152_215.3336_-31.7279.fits',
 '/cutouts/dr10/216/238336_grz_152_216.7971_-32.9485.fits',
 '/cutouts/dr10/216/3615482_grz_152_216.1907_-32.9446.fits',
 '/cutouts/dr10/217/4163217_grz_152_217.0036_-32.9357.fits',
 '/cutouts/dr10/216/238548_grz_152_216.1063_-32.9112.fits',
 '/cutouts/dr10/217/4174037_grz_152_217.5846_-32.8869.fits',
 '/cutouts/dr10/216/3614326_grz_152_216.2875_-32.8545.fits',
 '/cutouts/dr10/216/3616754_grz_152_216.5781_-32.8420.fits',
 '/cutouts/dr10/217/4167244_grz_152_217.1252_-32.6669.fits',
 '/cutouts/dr10/216/3616949_grz_152_216.5383_-32.5250.fits',
 '/cutouts/dr10/217/3864254_grz_152_217.3647_-32.4976.fits',
 '/cutouts/dr10/216/241712_grz_152_216.3076_-32.3942.fits',
 '/cutouts/dr10/216/3613038_grz_152_216.3087_-32.3873.fits',
 '/cutouts/dr10/216/241858_grz_152_216.1864_-32.3649.fits',
 '/cutouts/dr10/217/242823_grz_152_217.2280_-32.1849.fits',
 '/cutouts/dr10/215/3615696_grz_152_215.9078_-32.1023.fits',
 '/cutouts/dr10/216/3627168_grz_152_216.6244_-32.0603.fits',
 '/cutouts/dr10/215/3626811_grz_152_215.9765_-31.8502.fits',
 '/cutouts/dr10/216/3616211_grz_152_216.0181_-31.7378.fits',
 '/cutouts/dr10/217/4257814_grz_152_217.0402_-31.7168.fits',
 '/cutouts/dr10/217/3145661_grz_152_217.1355_-31.6635.fits',
 '/cutouts/dr10/216/246317_grz_152_216.3468_-31.3829.fits',
 '/cutouts/dr10/216/3621791_grz_152_216.7252_-31.3294.fits',
 '/cutouts/dr10/216/3145653_grz_152_216.8827_-31.2389.fits',
 '/cutouts/dr10/216/247260_grz_152_216.7348_-31.1583.fits',
 '/cutouts/dr10/216/3618402_grz_152_216.5050_-31.0826.fits',
 '/cutouts/dr10/216/802521_grz_152_216.8272_-30.9546.fits',
 '/cutouts/dr10/216/802469_grz_152_216.7508_-30.9480.fits',
 '/cutouts/dr10/216/3632432_grz_152_216.8071_-30.9364.fits',
 '/cutouts/dr10/216/3615770_grz_152_216.6713_-30.8990.fits',
 '/cutouts/dr10/221/3636297_grz_152_221.5203_-30.3355.fits',
 '/cutouts/dr10/221/3642153_grz_152_221.5357_-30.3055.fits',
 '/cutouts/dr10/221/3639629_grz_152_221.5125_-30.2359.fits',
 '/cutouts/dr10/221/3633288_grz_152_221.3122_-30.0785.fits',
 '/cutouts/dr10/221/3646809_grz_152_221.5706_-30.0456.fits',
 '/cutouts/dr10/221/3648684_grz_152_221.5780_-30.0430.fits',
 '/cutouts/dr10/221/3635441_grz_152_221.4126_-30.0234.fits',
 '/cutouts/dr10/221/3633260_grz_152_221.5290_-29.9790.fits',
 '/cutouts/dr10/221/252378_grz_152_221.3080_-29.9769.fits',
 '/cutouts/dr10/221/252834_grz_152_221.6699_-29.8669.fits',
 '/cutouts/dr10/221/253166_grz_152_221.4038_-29.7815.fits',
 '/cutouts/dr10/221/3636406_grz_152_221.4650_-29.7472.fits',
 '/cutouts/dr10/221/3641491_grz_152_221.1070_-29.7387.fits',
 '/cutouts/dr10/221/253360_grz_152_221.4429_-29.7352.fits',
 '/cutouts/dr10/221/253722_grz_152_221.4519_-29.6531.fits',
 '/cutouts/dr10/221/254373_grz_152_221.9276_-29.4963.fits',
 '/cutouts/dr10/221/3637319_grz_152_221.4012_-29.3585.fits',
 '/cutouts/dr10/221/255029_grz_152_221.2464_-29.3454.fits',
 '/cutouts/dr10/220/3655144_grz_152_220.9061_-29.3229.fits',
 '/cutouts/dr10/222/3635480_grz_152_222.0188_-29.2755.fits',
 '/cutouts/dr10/221/3635373_grz_152_221.9423_-29.2721.fits',
 '/cutouts/dr10/221/3638239_grz_152_221.0530_-29.2355.fits',
 '/cutouts/dr10/221/255533_grz_152_221.9326_-29.2328.fits',
 '/cutouts/dr10/222/255579_grz_152_222.1396_-29.2213.fits',
 '/cutouts/dr10/221/3635516_grz_152_221.8697_-29.1257.fits',
 '/cutouts/dr10/222/3646505_grz_152_222.0790_-29.1093.fits',
 '/cutouts/dr10/221/5083550_grz_152_221.4389_-29.0824.fits',
 '/cutouts/dr10/221/3642787_grz_152_221.1117_-29.0572.fits',
 '/cutouts/dr10/219/3634446_grz_152_219.4485_-29.1419.fits',
 '/cutouts/dr10/219/255510_grz_152_219.6538_-29.2369.fits',
 '/cutouts/dr10/219/3648465_grz_152_219.7063_-29.7663.fits',
 '/cutouts/dr10/219/3636022_grz_152_219.7905_-29.6577.fits',
 '/cutouts/dr10/219/3650018_grz_152_219.7409_-29.7362.fits',
 '/cutouts/dr10/220/254686_grz_152_220.1293_-29.4246.fits',
 '/cutouts/dr10/220/3636433_grz_152_220.1202_-29.4467.fits',
 '/cutouts/dr10/220/804138_grz_152_220.1611_-29.6056.fits',
 '/cutouts/dr10/220/3649166_grz_152_220.1593_-29.6098.fits',
 '/cutouts/dr10/220/3642415_grz_152_220.2145_-29.5400.fits',
 '/cutouts/dr10/220/255782_grz_152_220.5704_-29.1724.fits',
 '/cutouts/dr10/220/3639495_grz_152_220.2612_-29.6446.fits',
 '/cutouts/dr10/220/254620_grz_152_220.5507_-29.4383.fits',
 '/cutouts/dr10/220/3638983_grz_152_220.5644_-29.4973.fits',
 '/cutouts/dr10/220/5097206_grz_152_220.4284_-29.8888.fits',
 '/cutouts/dr10/220/3636463_grz_152_220.7162_-29.4584.fits',
 '/cutouts/dr10/220/3650628_grz_152_220.7562_-29.4163.fits',
 '/cutouts/dr10/220/3647910_grz_152_220.8442_-29.2876.fits',
 '/cutouts/dr10/220/4168518_grz_152_220.2293_-30.2981.fits',
 '/cutouts/dr10/220/4294021_grz_152_220.9506_-29.5987.fits',
 '/cutouts/dr10/220/3638912_grz_152_220.8678_-29.7670.fits',
 '/cutouts/dr10/220/3637788_grz_152_220.8838_-29.7940.fits',
 '/cutouts/dr10/221/4294012_grz_152_221.0563_-29.7205.fits',
 '/cutouts/dr10/221/3635483_grz_152_221.0921_-29.7523.fits',
 '/cutouts/dr10/220/3145802_grz_152_220.4986_-30.7012.fits',
 '/cutouts/dr10/220/3617852_grz_152_220.6301_-30.7201.fits',
 '/cutouts/dr10/220/3637775_grz_152_220.8761_-30.5071.fits',
 '/cutouts/dr10/221/3639926_grz_152_221.3460_-30.3158.fits',
 '/cutouts/dr10/221/248438_grz_152_221.0648_-30.8852.fits',
 '/cutouts/dr10/219/3635343_grz_152_219.2838_-29.1149.fits',
 '/cutouts/dr10/219/3145753_grz_152_219.1502_-29.0567.fits',
 '/cutouts/dr10/219/3650701_grz_152_219.0955_-29.2485.fits',
 '/cutouts/dr10/218/4183012_grz_152_218.9866_-29.1092.fits',
 '/cutouts/dr10/218/256074_grz_152_218.9038_-29.0983.fits',
 '/cutouts/dr10/218/3654546_grz_152_218.9157_-29.2622.fits',
 '/cutouts/dr10/218/3635711_grz_152_218.9122_-29.2595.fits',
 '/cutouts/dr10/218/3637917_grz_152_218.8918_-29.4905.fits',
 '/cutouts/dr10/218/3145744_grz_152_218.7883_-29.3114.fits',
 '/cutouts/dr10/218/3651095_grz_152_218.9333_-29.6712.fits',
 '/cutouts/dr10/218/3643325_grz_152_218.7651_-29.4340.fits',
 '/cutouts/dr10/218/4183702_grz_152_218.7140_-29.3595.fits',
 '/cutouts/dr10/218/255346_grz_152_218.6631_-29.2740.fits',
 '/cutouts/dr10/218/5074044_grz_152_218.7958_-29.6231.fits',
 '/cutouts/dr10/218/4171142_grz_152_218.5942_-29.3329.fits',
 '/cutouts/dr10/218/4173519_grz_152_218.5593_-29.2647.fits',
 '/cutouts/dr10/218/3643675_grz_152_218.7090_-29.6666.fits',
 '/cutouts/dr10/218/254367_grz_152_218.5882_-29.4978.fits',
 '/cutouts/dr10/218/252620_grz_152_218.7537_-29.9185.fits',
 '/cutouts/dr10/218/3636010_grz_152_218.7551_-29.9238.fits',
 '/cutouts/dr10/218/3643365_grz_152_218.7421_-29.9269.fits',
 '/cutouts/dr10/218/4257457_grz_152_218.7135_-29.9484.fits',
 '/cutouts/dr10/218/4170141_grz_152_218.6650_-29.8822.fits',
 '/cutouts/dr10/218/4170976_grz_152_218.5758_-30.0700.fits',
 '/cutouts/dr10/218/4162826_grz_152_218.2655_-29.4810.fits',
 '/cutouts/dr10/217/4174163_grz_152_217.9202_-29.0680.fits',
 '/cutouts/dr10/218/3864281_grz_152_218.2875_-29.9158.fits',
 '/cutouts/dr10/218/252944_grz_152_218.2366_-29.8377.fits',
 '/cutouts/dr10/218/4184564_grz_152_218.0096_-29.3576.fits',
 '/cutouts/dr10/218/248874_grz_152_218.8646_-30.7884.fits',
 '/cutouts/dr10/218/4177786_grz_152_218.8265_-30.7337.fits',
 '/cutouts/dr10/219/4171104_grz_152_219.8582_-30.7195.fits',
 '/cutouts/dr10/219/4263398_grz_152_219.4677_-30.6873.fits',
 '/cutouts/dr10/219/249422_grz_152_219.3542_-30.6626.fits',
 '/cutouts/dr10/219/3864327_grz_152_219.5369_-30.6524.fits',
 '/cutouts/dr10/220/4257821_grz_152_220.0217_-30.6360.fits',
 '/cutouts/dr10/219/4186655_grz_152_219.3738_-30.5997.fits',
 '/cutouts/dr10/219/4184685_grz_152_219.3224_-30.5130.fits',
 '/cutouts/dr10/218/4176933_grz_152_218.5810_-30.5105.fits',
 '/cutouts/dr10/219/3153857_grz_152_219.2925_-30.4781.fits',
 '/cutouts/dr10/218/250540_grz_152_218.7267_-30.3993.fits',
 '/cutouts/dr10/219/4257820_grz_152_219.0808_-30.3784.fits',

In [ ]:
from dataset_builder import build_training_dataset

final_df = build_training_dataset(
    target_df=df,
    anchor_df=anchor_df,
    output_path="classifier_ready.csv"
)